networks:
  shopping-network:
    name: shopping-network
    driver: bridge

volumes:
  redis-data:
    name: redis-data
  kafka-data:
    name: kafka-data


services:
  # Redis Caching Service
  redis-caching:
    image: redis:8.4.0
    container_name: redis-caching
    hostname: redis-caching
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - shopping-network


  # Kafka Broker Service
  kafka-broker:
    image: confluentinc/cp-kafka:7.7.7
    container_name: kafka-broker
    hostname: kafka-broker
    environment:
      # Basic Kafka Settings
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka-broker:9093"

      KAFKA_LISTENERS: "INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka-broker:9092,EXTERNAL://localhost:9094"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"

      # Kraft Mode Settings
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 24
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    ports:
      - "9092:9092" # Internal communication
      - "9094:9094" # External communication (Debug)
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - shopping-network
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9094 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  # Kong Gateway (Declarative mode - no database needed)
  kong-gateway:
    image: kong:3.9.1
    container_name: kong-gateway
    hostname: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000, 0.0.0.0:8443 ssl
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      REDIS_PASSWORD: myredis
      KONG_UNTRUSTED_LUA: "on"
    ports:
      - "80:8000"         # HTTP Public
      - "443:8443"        # HTTPS Public
      - "8000:8000"       # Kong Proxy (HTTP Debug)
      - "8001:8001"       # Admin API cho decK (Debug)
    volumes:
      - ${KONG_CONFIG_FILE}:/usr/local/kong/declarative/kong.yml
      - ./user-service/secrets:/user-service/secrets
    networks:
      - shopping-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5


  # User Service
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    hostname: user-service
    image: user-service:v1.0.0
    depends_on:
      redis-caching:
        condition: service_healthy
      kafka-broker:
        condition: service_healthy
      kong-gateway:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES}

      - KAFKA_BOOTSTRAP_SERVERS=kafka-broker:9092
    env_file:
      - .env
      - user-service/.env
    ports:
      - "9001:8000" # Access via localhost:9001
    volumes:
      - ./user-service:/app/user-service
      - /app/user-service/.venv  # Exclude virtual environment
    networks:
      - shopping-network
    restart: unless-stopped


  # Recipe Service
  recipe-service:
    build:
      context: .
      dockerfile: recipe-service/Dockerfile
    container_name: recipe-service
    hostname: recipe-service
    image: recipe-service:v1.0.0
    depends_on:
      kafka-broker:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES}

      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - USER_SERVICE_URL=http://user-service:8000
    env_file:
      - .env
    ports:
      - "9002:8000" # Access via localhost:9002
    networks:
      - shopping-network
    restart: unless-stopped


  # Meal Service
  meal-service:
    build:
      context: .
      dockerfile: meal-service/Dockerfile
    image: meal-service:v1.0.0
    container_name: meal-service
    hostname: meal-service
    depends_on:
      kafka-broker:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES}

      - USER_SERVICE_URL=http://user-service:8000
    env_file:
      - .env
    ports:
      - "9003:8000" # Access via localhost:9003
    networks:
      - shopping-network
    restart: unless-stopped


  # Shopping Storage Service
  shopping-storage-service:
    build:
      context: .
      dockerfile: shopping-storage-service/Dockerfile
    image: shopping-storage-service:v1.0.0
    container_name: shopping-storage-service
    hostname: shopping-storage-service
    depends_on:
      kafka-broker:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES}

      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}

      - USER_SERVICE_URL=http://user-service:8000
    env_file:
      - .env
    ports:
      - "9004:8000" # Access via localhost:9004
    networks:
      - shopping-network
    restart: unless-stopped


  # Notification service
  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    image: notification-service:v1.0.0
    hostname: notification-service
    depends_on:
      redis-caching:
        condition: service_healthy
      kafka-broker:
        condition: service_healthy
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DECODE_RESPONSES=${REDIS_DECODE_RESPONSES}

      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    env_file:
      - .env
      - notification-service/.env
    ports:
      - "9005:8000" # Access via localhost:9005
    volumes:
      - ./notification-service:/app/notification-service
      - /app/notification-service/.venv  # Exclude virtual environment
    networks:
      - shopping-network
    restart: unless-stopped