services:
  shopping-storage-service:
    build: ./microservices/shopping-storage-service
    ports:
      - "9995:8000"
    profiles:
      - shopping-storage
    depends_on:
      - recipe-service

  recipe-service:
    build: ./micorservices/recipe-service
    profiles:
        - recipe-service
    ports:
      - "9996:8001"