# convenient-shopping-system/docker-compose.override.yml

# Ghi đè dịch vụ 'kong'
services:
  kong-gateway:
    volumes:
      # Ghi đè 'volumes' để trỏ đến tệp config local
      - ./api-gateway/kong.local.yml:/usr/local/kong/declarative/kong.yml