title: "Convenient Shopping System"
description: "Technical documentation about system design" 
baseurl: "/convenient-shopping-system"
url: "https://cuongct220020.github.io"

# Sử dụng remote_theme thay vì theme
remote_theme: just-the-docs/just-the-docs@v0.10.1

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme # Bắt buộc phải thêm plugin này để chạy Just the Docs

# Cấu hình MathJax cho các công thức AI/Deep Learning (SDE, Flow Matching)
markdown: kramdown
math: mathjax